docs(samples): added recaptcha code samples and tests
googleapis/python-recaptcha-enterprise pull request #112
Opened 2021-08-27 19:29 UTC by Sita04

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-recaptcha-enterprise/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #111  🦕

2021-08-27 20:27 UTC, kurtisvg requested changes
I activated the API on the project, but looks like you are still having some test failures.

2021-09-03 08:43 UTC, Sita04 commented on samples/snippets/app.py
> +def create_app():
Included it as part of the file. Thanks.

2021-09-03 08:44 UTC, Sita04 commented on samples/snippets/site_key.py
> +# [START recaptcha_enterprise_delete_site_key]
Created individual snippets.

2021-09-03 08:44 UTC, Sita04 commented on samples/snippets/test_create_assessment.py
> +    def test_create_assessment(self, capsys: typing.Any, recaptcha_site_key, browser) -> None:
Modified it to use CaptureFixture.

2021-09-03 08:45 UTC, Sita04 commented on samples/snippets/test_site_key.py
> +    recaptcha_site_key = site_key.main(GOOGLE_CLOUD_PROJECT, DOMAIN_NAME)
Totally agree with the approach. Modified it.

2021-10-11 06:44 UTC, Sita04 commented on .kokoro/docker/samples/Dockerfile
> +# TODO: Add Chrome Installation Here
Thank you very much Bu Sun!

2021-10-12 10:53 UTC, parthea commented
I've updated permissions and tests are passing now! I've added the `owlbot:run` label to enable the python3.10 samples.

2021-10-12 15:04 UTC, kurtisvg approved these changes

2021-10-12 15:04 UTC, kurtisvg commented on samples/snippets/create_assessment.py
> +    else:
nit: This else would be more readable as a return at the end of the prior clause instead

2021-10-12 15:04 UTC, kurtisvg commented on samples/snippets/create_assessment.py
> +        else:
nit: same here, but reversed - it's easier to read code if it's
```
if error
    # handle error
    return
# normal flow
``` 
as opposed to
```
if valid:
   # normal flow
else:
  # error handling

2021-10-13 11:31 UTC, parthea approved these changes

2021-10-13 11:33 UTC, merged